language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install pytest pytest-mock pylint docker flask
  
script:
  - pylint uma test || true
  - (cd test/units; pytest)
  - (cd test/integration; pytest -v)
